"""a conversation carries its reasoning effort

Effort reached a run only from a summon, and only for the run the summon
started: every turn after it went out at the runtime's default, and nothing
let the console change that mid-thread. The level goes on the conversation, as
its approval posture does, and each run reads it unless it was handed one of
its own. Existing rows stay NULL — nothing declared, which is what every turn
has run under until now.

Revision ID: 6d1fcc656563
Revises: a3904c3e3cf6
Create Date: 2026-10-06 21:24:00.947252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d1fcc656563"
down_revision: str | Sequence[str] | None = "a3904c3e3cf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "effort",
                sa.String(),
                nullable=True,
                comment="Reasoning effort this conversation's runs ask for, one of the levels its agent's route claims for the model. NULL is nothing declared, and the runtime's own default decides. A run given an effort of its own, as a summon is, uses that one instead.",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_column("effort")

    # ### end Alembic commands ###
