"""external_agent_run_variant

Revision ID: 7a3e9c1b2f8d
Revises: 924f7e1ce5ac
Create Date: 2026-07-15 15:30:00.000000

Single-table inheritance for `agent_runs`: a `kind` discriminator ('octomate' |
'external') plus the nullable columns of the `external` variant (a native run rebuilt
from an external runtime's transcript). Backfills existing rows — the runs restore has
already written (`name = 'claude-native'`) become 'external', carrying the session id
off their conversation's `external_id`.

Hand-written (not autogenerated) so it never opens the real DB during authoring; SQLite
adds columns in place (no table rebuild), so the FKs from `model_messages` are untouched.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a3e9c1b2f8d"
down_revision: str | Sequence[str] | None = "924f7e1ce5ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "agent_runs",
        sa.Column("kind", sa.String(), nullable=False, server_default="octomate"),
    )
    op.add_column(
        "agent_runs", sa.Column("external_session_id", sa.String(), nullable=True)
    )
    op.add_column("agent_runs", sa.Column("source", sa.String(), nullable=True))
    op.add_column("agent_runs", sa.Column("start_offset", sa.Integer(), nullable=True))
    op.add_column("agent_runs", sa.Column("end_offset", sa.Integer(), nullable=True))
    op.add_column("agent_runs", sa.Column("last_line_uuid", sa.String(), nullable=True))
    op.create_index(op.f("ix_agent_runs_kind"), "agent_runs", ["kind"], unique=False)
    op.create_index(
        op.f("ix_agent_runs_external_session_id"),
        "agent_runs",
        ["external_session_id"],
        unique=False,
    )
    # The runs restore wrote become the 'external' variant, with the external session id
    # copied off their conversation (where it lived as `external_id`).
    op.execute("UPDATE agent_runs SET kind = 'external' WHERE name = 'claude-native'")
    op.execute(
        """
        UPDATE agent_runs
        SET external_session_id = (
            SELECT external_id FROM conversations
            WHERE conversations.id = agent_runs.conversation_id
        )
        WHERE kind = 'external'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_agent_runs_external_session_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_kind"), table_name="agent_runs")
    op.drop_column("agent_runs", "last_line_uuid")
    op.drop_column("agent_runs", "end_offset")
    op.drop_column("agent_runs", "start_offset")
    op.drop_column("agent_runs", "source")
    op.drop_column("agent_runs", "external_session_id")
    op.drop_column("agent_runs", "kind")
