"""a run stays while any history includes it

A fork shares its source's runs through `conversation_runs` instead of copying
them, but each reference cascaded from its run: deleting the source conversation
deleted the runs it ran, and every fork's history of them went too. The
reference no longer cascades, so the database refuses to delete a run that any
history still includes, and with it a conversation whose runs a fork includes.
A conversation no fork shares still deletes with its runs.

Revision ID: c74cc1b5a108
Revises: 596190e89aa2
Create Date: 2026-10-08 22:31:07.222992

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c74cc1b5a108"
down_revision: str | Sequence[str] | None = "596190e89aa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # The reference was created unnamed; the convention names it on reflection.
    with op.batch_alter_table(
        "conversation_runs",
        schema=None,
        naming_convention={
            "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"
        },
    ) as batch_op:
        batch_op.drop_constraint(
            "fk_conversation_runs_run_id_agent_runs", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_conversation_runs_run_id_agent_runs",
            "agent_runs",
            ["run_id"],
            ["id"],
            ondelete="NO ACTION",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_runs", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_conversation_runs_run_id_agent_runs", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_conversation_runs_run_id_agent_runs",
            "agent_runs",
            ["run_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
