"""Persist one short-lived browser handoff per observed channel profile.

Only the ticket digest reaches the database. The unique profile row and optimistic
version make replacement and consumption serialize around the identity being bound.

Revision ID: 2dca6fab4aca
Revises: ebb904508e50
Create Date: 2026-09-12 18:02:23.232332

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import octomate.models.base

# revision identifiers, used by Alembic.
revision: str = "2dca6fab4aca"
down_revision: str | Sequence[str] | None = "ebb904508e50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_binding_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "profile_id",
            sa.Uuid(),
            nullable=False,
            comment="The exact channel profile this session may bind.",
        ),
        sa.Column(
            "token_hash",
            octomate.models.base.SecretString(),
            nullable=False,
            comment="SHA-256 digest of the one-time URL ticket; never stores the ticket.",
        ),
        sa.Column(
            "expires_at",
            octomate.models.base.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            octomate.models.base.UTCDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "consumed_at",
            octomate.models.base.UTCDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
            comment="Optimistic lock preventing the same profile ticket from binding twice.",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["user_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("profile_binding_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_profile_binding_sessions_consumed_at"),
            ["consumed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_profile_binding_sessions_expires_at"),
            ["expires_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile_binding_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_binding_sessions_expires_at"))
        batch_op.drop_index(batch_op.f("ix_profile_binding_sessions_consumed_at"))

    op.drop_table("profile_binding_sessions")
    # ### end Alembic commands ###
