"""a chat room kick works in a sub-thread

A dm and a group chat have no end, so a conversation held against one would grow
for as long as the chat room does. The work of answering a message there happens in
a thread of its own instead, while the chat everyone sees stays on the chat room.
`parent_thread_id` is the link, one level deep.

`uq_thread_messages_delivery` comes with it rather than after it. A platform re-sends
a message when it misses an ack, and a duplicate row used to be only a duplicate;
once a kick opens a thread of its own it is a second answer as well. `direction` is
part of that key because a native runtime files a turn's prompt and the answer to it
under one id — the pair is what its transcript names, so the id alone never was
unique.

Two adjustments to what autogenerate produced. The foreign key is named, as the
self-reference on `conversations` was — batch mode renders it unnamed and SQLite
refuses that. And `uq_threads_chat` is recreated by hand: a sub-thread shares its
chat room's address, so the index that pins one row per chat has to let it past,
and alembic compares an index's columns but not its `sqlite_where`, so it sees no
change to generate. Without this the model and a migrated database disagree in the
one way the tests cannot catch — they build their schema from the model directly.

Revision ID: 0d0112888c17
Revises: 1036c4c4f86b
Create Date: 2026-09-05 02:00:23.667484

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d0112888c17"
down_revision: str | Sequence[str] | None = "1036c4c4f86b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "parent_thread_id",
                sa.Uuid(),
                nullable=True,
                comment="The thread this one was opened inside. A dm and a group chat have no end, so the work of answering one message there is a thread of its own, while the chat everyone sees stays on the chat room. NULL for a thread nobody opened. One level deep: a sub-thread never becomes a parent, so a thread's ledger is its own or its parent's, never further up.",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_threads_parent_thread_id"),
            ["parent_thread_id"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_threads_parent_thread_id",
            "threads",
            ["parent_thread_id"],
            ["id"],
            ondelete="CASCADE",
        )

    op.drop_index("uq_threads_chat", table_name="threads")
    op.create_index(
        "uq_threads_chat",
        "threads",
        ["channel_tentacle_id", "chat_type", "chat_id"],
        unique=True,
        sqlite_where=sa.text("channel_thread_id IS NULL AND parent_thread_id IS NULL"),
    )

    with op.batch_alter_table("thread_messages", schema=None) as batch_op:
        batch_op.create_index(
            "uq_thread_messages_delivery",
            ["thread_id", "platform_message_id", "direction"],
            unique=True,
            sqlite_where=sa.text("platform_message_id IS NOT NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("thread_messages", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_thread_messages_delivery",
            sqlite_where=sa.text("platform_message_id IS NOT NULL"),
        )

    op.drop_index("uq_threads_chat", table_name="threads")
    op.create_index(
        "uq_threads_chat",
        "threads",
        ["channel_tentacle_id", "chat_type", "chat_id"],
        unique=True,
        sqlite_where=sa.text("channel_thread_id IS NULL"),
    )
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_constraint("fk_threads_parent_thread_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_threads_parent_thread_id"))
        batch_op.drop_column("parent_thread_id")

    # ### end Alembic commands ###
