"""a thread and a session carry a name

A listing is served without its messages — reading one line per thread would be
a request per row — so a thread had nothing to be called but the surface it
lives on, and a native session's surface is a uuid. The name goes on the row:
written from the first thing a person said in the thread, and replaced by the
name the runtime grabbed for itself where there is one.

The backfill gives every thread that already exists the same opening line a new
one would get, so a reader sees one rule rather than two. Claude's own titles
are not backfilled — they arrive from the transcript, and land the next time a
session's tail runs.

Revision ID: bdb96422fcdc
Revises: 72af5e4bed47
Create Date: 2026-09-02 02:27:04.763975

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdb96422fcdc"
down_revision: str | Sequence[str] | None = "72af5e4bed47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The manager's own limit, restated because a migration outlives the code that
# produced it and must keep meaning what it meant when it ran.
TITLE_MAX = 72

OPENING_LINES = sa.text(
    "SELECT thread_id, message_text FROM thread_messages "
    "WHERE direction = 'inbound' AND actor_kind = 'human' "
    "AND message_text IS NOT NULL AND message_text != '' "
    "ORDER BY happened_at"
)

NAME_THREAD = sa.text(
    "UPDATE threads SET title = :title WHERE id = :id AND title IS NULL"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "title",
                sa.String(),
                nullable=True,
                comment="What this thread goes by in a listing. Taken from the first thing a person said in it, and replaced by a name the runtime grabbed for itself — a Claude session's own ai-title, which is about the work rather than about its opening line. NULL until the thread has been spoken in, and a listing then falls back to the surface.",
            )
        )

    # ### end Alembic commands ###
    connection = op.get_bind()
    named: set[object] = set()
    for thread_id, message_text in connection.execute(OPENING_LINES):
        if thread_id in named:
            continue
        line = " ".join((message_text or "").split())
        if not line:
            continue
        named.add(thread_id)
        connection.execute(
            NAME_THREAD,
            {
                "id": thread_id,
                "title": line
                if len(line) <= TITLE_MAX
                else f"{line[:TITLE_MAX].rstrip()}…",
            },
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("threads", schema=None) as batch_op:
        batch_op.drop_column("title")

    # ### end Alembic commands ###
