"""commands, effort, and shared histories

Explicit command deliveries stay out of ordinary chat prompts. Command receipts
share the ledger delivery key and retain typed intent and outcomes. Existing rows
remain messages. SQLite batch recreation must retain the ledger's search
triggers so history indexing continues after either migration direction.

Effort reached a run only from a summon, and only for the run the summon
started: every turn after it went out at the runtime's default, and nothing let
the console change that mid-thread. The level goes on the conversation, as its
approval posture does, and each run reads it unless it was handed one of its
own. Existing rows stay NULL — nothing declared, which is what every turn has
run under until now.

A conversation's history was the runs it ran, and a thread's chat the messages
delivered to it, so a fork could only show its source's history by copying every
run, model message, chat message and binding under new ids. Each history now
reads through a junction. `conversation_runs` names the runs a conversation's
history is made of. `thread_ledgers` names the ledgers a thread shows — the
messages delivered to a thread — each up to a cut, so a fork points at its
source's ledgers frozen where they stood instead of copying them. A run
reference does not cascade from its run: the database refuses to delete a run
that any history still includes, and with it a conversation whose runs a fork
includes.

Every existing run is backfilled into the history of the conversation it ran in,
and every thread into its own ledger, shown whole: what each new one joins as it
is written. Downgrading drops the junctions and with them whatever a fork only
pointed at.

Revision ID: 9413e47fcf52
Revises: 4f9cac50c4f8
Create Date: 2026-10-08 23:23:07.192039

"""

from collections.abc import Generator, Sequence
from contextlib import contextmanager

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9413e47fcf52"
down_revision: str | Sequence[str] | None = "4f9cac50c4f8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


@contextmanager
def preserve_ledger_triggers() -> Generator[None]:
    """Batch table recreation drops SQLite triggers; retain their exact definitions."""
    triggers = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT sql FROM sqlite_master WHERE type = 'trigger' AND tbl_name = 'thread_messages'"
            )
        )
        .scalars()
        .all()
    )
    yield
    for trigger in triggers:
        op.execute(trigger)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_ledgers",
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ledger_id",
            sa.Uuid(),
            nullable=False,
            comment="The thread whose delivered messages make up this ledger.",
        ),
        sa.Column(
            "cut_message_id",
            sa.Uuid(),
            nullable=True,
            comment="The ledger's last message this thread shows, frozen at the fork that shared it. NULL only for the thread's own ledger, shown whole as it grows.",
        ),
        sa.ForeignKeyConstraint(
            ["cut_message_id"],
            ["thread_messages.id"],
        ),
        sa.ForeignKeyConstraint(["ledger_id"], ["threads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("thread_id", "ledger_id"),
    )
    with op.batch_alter_table("thread_ledgers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_thread_ledgers_ledger_id"), ["ledger_id"], unique=False
        )

    op.create_table(
        "conversation_runs",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "run_id",
            sa.String(),
            nullable=False,
            comment="Not cascaded: a run cannot be deleted while any history includes it, so a conversation whose runs a fork still includes cannot be deleted. Not RESTRICT either, which SQLite checks mid-statement, before the deleted conversation's own references are sure to be gone.",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name="fk_conversation_runs_run_id_agent_runs",
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("conversation_id", "run_id"),
    )
    with op.batch_alter_table("conversation_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_runs_run_id"), ["run_id"], unique=False
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "effort",
                sa.String(),
                nullable=True,
                comment="Reasoning effort this conversation's runs ask for, one of the levels its agent's route claims for the model. NULL is nothing declared, and the runtime's own default decides. A run given an effort of its own, as a summon is, uses that one instead.",
            )
        )

    with (
        preserve_ledger_triggers(),
        op.batch_alter_table("thread_messages", schema=None) as batch_op,
    ):
        batch_op.add_column(
            sa.Column(
                "kind",
                sa.String(),
                server_default="message",
                nullable=False,
                comment="Whether this ledger row is a chat message or an explicit command.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "conversation_id",
                sa.Uuid(),
                nullable=True,
                comment="The command's target conversation; NULL after that conversation is deleted.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "invocation",
                sa.JSON(),
                nullable=True,
                comment="Explicit command intent with raw arguments and resolved attachments.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "outcome",
                sa.JSON(none_as_null=True),
                nullable=True,
                comment="Recorded command outcome; NULL means no terminal outcome was recorded, not permission to retry.",
            )
        )
        batch_op.create_foreign_key(
            "fk_thread_command_conversation",
            "conversations",
            ["conversation_id"],
            ["id"],
            ondelete="SET NULL",
            use_alter=True,
        )

    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO thread_ledgers (thread_id, ledger_id) SELECT id, id FROM threads"
    )
    op.execute(
        "INSERT INTO conversation_runs (conversation_id, run_id) "
        "SELECT conversation_id, id FROM agent_runs"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with (
        preserve_ledger_triggers(),
        op.batch_alter_table("thread_messages", schema=None) as batch_op,
    ):
        batch_op.drop_constraint("fk_thread_command_conversation", type_="foreignkey")
        batch_op.drop_column("outcome")
        batch_op.drop_column("invocation")
        batch_op.drop_column("conversation_id")
        batch_op.drop_column("kind")

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_column("effort")

    with op.batch_alter_table("conversation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_runs_run_id"))

    op.drop_table("conversation_runs")
    with op.batch_alter_table("thread_ledgers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thread_ledgers_ledger_id"))

    op.drop_table("thread_ledgers")
    # ### end Alembic commands ###
