"""give project an upstream

`projects` gains `upstream`: where a project's mirror comes from and how it is kept
current. A `remote` upstream carries a url that is cloned and fetched; a `directory`
upstream carries a path that is `git init`'d and synced by copying in and committing.
Nothing reads the column yet — this revision is the storage for it.

Existing rows are backfilled as a directory upstream at their own root: every project
in the registry today was registered from a local directory, so that is what its
mirror will sync from. The column is added nullable, backfilled, then tightened to
NOT NULL, because SQLite cannot add a NOT NULL column without a server default to a
table that already has rows.

Revision ID: f54a9afc1e44
Revises: 02823d5dcce5
Create Date: 2026-08-18 18:52:18.300721

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f54a9afc1e44"
down_revision: str | Sequence[str] | None = "02823d5dcce5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema, then backfill every existing row with the upstream it has."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "upstream",
                sa.JSON(),
                nullable=True,
                comment="Where this project's mirror comes from and how it is kept current: kind `remote` carries a url that is cloned and fetched; kind `directory` carries a path that is `git init`'d and synced by copying in and committing.",
            )
        )

    # ### end Alembic commands ###

    op.execute(
        "UPDATE projects SET upstream = json_object('kind', 'directory', 'path', root)"
    )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.alter_column("upstream", existing_type=sa.JSON(), nullable=False)


def downgrade() -> None:
    """Downgrade schema.

    A remote upstream an operator declared is not carried anywhere: nothing in the
    old schema can hold it, and re-upgrading backfills every row from its root again.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("upstream")

    # ### end Alembic commands ###
