"""conversations and threads read history through runs and ledgers

A conversation's history was the runs it ran, and a thread's chat the messages
delivered to it, so a fork could only show its source's history by copying every
run, model message, chat message and binding under new ids. Each history now
reads through a junction. `conversation_runs` names the runs a conversation's
history is made of. `thread_ledgers` names the ledgers a thread shows — the
messages delivered to a thread — each up to a cut, so a fork points at its
source's ledgers frozen where they stood instead of copying them.

Every existing run is backfilled into the history of the conversation it ran in,
and every thread into its own ledger, shown whole: what each new one joins as it
is written. Downgrading drops the junctions and with them whatever a fork only
pointed at.

Revision ID: 596190e89aa2
Revises: 6d1fcc656563
Create Date: 2026-10-08 20:03:18.157504

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "596190e89aa2"
down_revision: str | Sequence[str] | None = "6d1fcc656563"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_ledgers",
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ledger_id",
            sa.Uuid(),
            nullable=False,
            comment="The thread whose delivered messages make up this ledger.",
        ),
        sa.Column(
            "cut_message_id",
            sa.Uuid(),
            nullable=True,
            comment="The ledger's last message this thread shows, frozen at the fork that shared it. NULL only for the thread's own ledger, shown whole as it grows.",
        ),
        sa.ForeignKeyConstraint(
            ["cut_message_id"],
            ["thread_messages.id"],
        ),
        sa.ForeignKeyConstraint(["ledger_id"], ["threads.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["threads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("thread_id", "ledger_id"),
    )
    with op.batch_alter_table("thread_ledgers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_thread_ledgers_ledger_id"), ["ledger_id"], unique=False
        )

    op.create_table(
        "conversation_runs",
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"], ["conversations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("conversation_id", "run_id"),
    )
    with op.batch_alter_table("conversation_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_runs_run_id"), ["run_id"], unique=False
        )

    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO thread_ledgers (thread_id, ledger_id) SELECT id, id FROM threads"
    )
    op.execute(
        "INSERT INTO conversation_runs (conversation_id, run_id) "
        "SELECT conversation_id, id FROM agent_runs"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_runs_run_id"))

    op.drop_table("conversation_runs")
    with op.batch_alter_table("thread_ledgers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thread_ledgers_ledger_id"))

    op.drop_table("thread_ledgers")
    # ### end Alembic commands ###
