"""initial: conversations + agent_runs + model_messages

Revision ID: 47f580284e75
Revises: 
Create Date: 2026-05-10 11:30:52.341104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import octomate.models.messages  # noqa: F401 — referenced by autogenerated PydanticJSON columns


# revision identifiers, used by Alembic.
revision: str = '47f580284e75'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_type', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel_tentacle_id', sa.String(), nullable=False),
    sa.Column('agent_tentacle_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_type', 'chat_id', 'thread_id', 'user_id', name='uq_conversations_conversation_key')
    )
    op.create_index(op.f('ix_conversations_agent_tentacle_id'), 'conversations', ['agent_tentacle_id'], unique=False)
    op.create_index(op.f('ix_conversations_channel_tentacle_id'), 'conversations', ['channel_tentacle_id'], unique=False)
    op.create_index(op.f('ix_conversations_chat_id'), 'conversations', ['chat_id'], unique=False)
    op.create_index(op.f('ix_conversations_thread_id'), 'conversations', ['thread_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_conversation_id'), 'agent_runs', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_started_at'), 'agent_runs', ['started_at'], unique=False)
    op.create_table('model_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('parts', octomate.models.messages.PydanticJSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('metadata', octomate.models.messages.PydanticJSON(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('usage', octomate.models.messages.PydanticJSON(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_url', sa.String(), nullable=True),
    sa.Column('provider_details', octomate.models.messages.PydanticJSON(), nullable=True),
    sa.Column('provider_response_id', sa.String(), nullable=True),
    sa.Column('finish_reason', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_messages_conversation_id'), 'model_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_model_messages_kind'), 'model_messages', ['kind'], unique=False)
    op.create_index(op.f('ix_model_messages_model_name'), 'model_messages', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_messages_provider_name'), 'model_messages', ['provider_name'], unique=False)
    op.create_index(op.f('ix_model_messages_provider_response_id'), 'model_messages', ['provider_response_id'], unique=False)
    op.create_index(op.f('ix_model_messages_run_id'), 'model_messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_model_messages_state'), 'model_messages', ['state'], unique=False)
    op.create_index(op.f('ix_model_messages_timestamp'), 'model_messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_messages_timestamp'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_state'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_run_id'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_provider_response_id'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_provider_name'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_model_name'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_kind'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_conversation_id'), table_name='model_messages')
    op.drop_table('model_messages')
    op.drop_index(op.f('ix_agent_runs_started_at'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_conversation_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_chat_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel_tentacle_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_tentacle_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
