"""conversation keyed by thread

A conversation is now one agent's context within a thread, identified by
``(thread_id, agent_tentacle_id)``. The denormalized channel-address columns
move to the owning thread, ``thread_id`` becomes mandatory, and its FK cascades
from the thread. Existing rows are dropped (no backfill).

Revision ID: 0d74b4984871
Revises: c1d2e3f4a5b6
Create Date: 2026-06-30 21:59:44.795838

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d74b4984871"
down_revision: Union[str, Sequence[str], None] = "c1d2e3f4a5b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Identity changes shape; conversations carry no human history, so drop them
    # (runs/messages cascade) rather than backfill — and so the new NOT NULL
    # thread_id has no null rows to reject.
    op.execute("DELETE FROM conversations")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "thread_id", existing_type=sa.CHAR(length=32), nullable=False
        )
        batch_op.drop_index(batch_op.f("ix_conversations_channel_tentacle_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_channel_thread_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_chat_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_user_id"))
        batch_op.drop_constraint(
            batch_op.f("uq_conversations_conversation_key"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_conversations_conversation_key", ["thread_id", "agent_tentacle_id"]
        )
        batch_op.drop_constraint(
            batch_op.f("fk_conversations_thread_id_threads"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_conversations_thread_id_threads",
            "threads",
            ["thread_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("chat_id")
        batch_op.drop_column("chat_type")
        batch_op.drop_column("channel_tentacle_id")
        batch_op.drop_column("user_id")
        batch_op.drop_column("channel_thread_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DELETE FROM conversations")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("channel_thread_id", sa.VARCHAR(), nullable=False)
        )
        batch_op.add_column(sa.Column("user_id", sa.VARCHAR(), nullable=False))
        batch_op.add_column(
            sa.Column("channel_tentacle_id", sa.VARCHAR(), nullable=False)
        )
        batch_op.add_column(sa.Column("chat_type", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("chat_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(
            "fk_conversations_thread_id_threads", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_conversations_thread_id_threads"),
            "threads",
            ["thread_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.drop_constraint("uq_conversations_conversation_key", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_conversations_conversation_key"),
            [
                "channel_tentacle_id",
                "chat_type",
                "chat_id",
                "channel_thread_id",
                "user_id",
                "agent_tentacle_id",
            ],
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_chat_id"), ["chat_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_channel_thread_id"),
            ["channel_thread_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_channel_tentacle_id"),
            ["channel_tentacle_id"],
            unique=False,
        )
        batch_op.alter_column(
            "thread_id", existing_type=sa.CHAR(length=32), nullable=True
        )

    # ### end Alembic commands ###
