"""add todos table

Revision ID: 6fadf2912338
Revises: 1299695210c6
Create Date: 2026-06-08 11:35:25.637525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import octomate.models.messages  # noqa: F401 — referenced by PydanticJSON columns


# revision identifiers, used by Alembic.
revision: str = '6fadf2912338'
down_revision: Union[str, Sequence[str], None] = '1299695210c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('active_form', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('parent_ref', sa.String(), nullable=True),
    sa.Column('depends_on', octomate.models.messages.PydanticJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'ref', name='uq_todos_conversation_ref')
    )
    op.create_index(op.f('ix_todos_conversation_id'), 'todos', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_todos_created_at'), 'todos', ['created_at'], unique=False)
    op.create_index(op.f('ix_todos_parent_ref'), 'todos', ['parent_ref'], unique=False)
    op.create_index(op.f('ix_todos_ref'), 'todos', ['ref'], unique=False)
    op.create_index(op.f('ix_todos_updated_at'), 'todos', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_updated_at'), table_name='todos')
    op.drop_index(op.f('ix_todos_ref'), table_name='todos')
    op.drop_index(op.f('ix_todos_parent_ref'), table_name='todos')
    op.drop_index(op.f('ix_todos_created_at'), table_name='todos')
    op.drop_index(op.f('ix_todos_conversation_id'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###
