"""initial: sessions + model_messages

Revision ID: 2abf19cdfa5b
Revises: 
Create Date: 2026-05-10 03:00:46.564405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import octomate.models.messages  # noqa: F401 — referenced by autogenerated PydanticJSON columns


# revision identifiers, used by Alembic.
revision: str = '2abf19cdfa5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_type', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel_tentacle_id', sa.String(), nullable=False),
    sa.Column('agent_tentacle_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_type', 'chat_id', 'thread_id', 'user_id', name='uq_sessions_session_key')
    )
    op.create_index(op.f('ix_sessions_agent_tentacle_id'), 'sessions', ['agent_tentacle_id'], unique=False)
    op.create_index(op.f('ix_sessions_channel_tentacle_id'), 'sessions', ['channel_tentacle_id'], unique=False)
    op.create_index(op.f('ix_sessions_chat_id'), 'sessions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_sessions_thread_id'), 'sessions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('model_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('parts', octomate.models.messages.PydanticJSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('metadata', octomate.models.messages.PydanticJSON(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('usage', octomate.models.messages.PydanticJSON(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_url', sa.String(), nullable=True),
    sa.Column('provider_details', octomate.models.messages.PydanticJSON(), nullable=True),
    sa.Column('provider_response_id', sa.String(), nullable=True),
    sa.Column('finish_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_messages_kind'), 'model_messages', ['kind'], unique=False)
    op.create_index(op.f('ix_model_messages_model_name'), 'model_messages', ['model_name'], unique=False)
    op.create_index(op.f('ix_model_messages_provider_name'), 'model_messages', ['provider_name'], unique=False)
    op.create_index(op.f('ix_model_messages_provider_response_id'), 'model_messages', ['provider_response_id'], unique=False)
    op.create_index(op.f('ix_model_messages_run_id'), 'model_messages', ['run_id'], unique=False)
    op.create_index(op.f('ix_model_messages_session_id'), 'model_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_model_messages_timestamp'), 'model_messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_messages_timestamp'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_session_id'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_run_id'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_provider_response_id'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_provider_name'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_model_name'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_kind'), table_name='model_messages')
    op.drop_table('model_messages')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_thread_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_chat_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_channel_tentacle_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_agent_tentacle_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
