"""a user's secret lives on their row

The deployment secret is retired: every configured credential names a person, so
each registered user's bearer belongs on their registry row, reconciled from
`users.<name>.secret` at boot the way `name` and `nickname` already are. The unique
constraint is the whole point of persisting it — a bearer must name exactly one
user, and the database is the one place that can promise it; two YAML entries
sharing a value now fail the boot at reconciliation instead of passing a validator
that could only check one config file at a time.

Nothing is carried: the column was never written before, so every existing row
starts NULL — registration happens at the next reconcile from whatever the YAML
declares. NULL stays legal, and multiple NULLs coexist under the constraint: a user
registered only to link channel accounts holds no credential at all.

The column is `SecretString` in the model — `SecretStr` above, text in the column —
whose impl is what renders here, exactly as `PathString` columns render `String`.

Revision ID: 72af5e4bed47
Revises: 02823d5dcce5
Create Date: 2026-08-31 01:06:24.711766

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72af5e4bed47"
down_revision: str | Sequence[str] | None = "02823d5dcce5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "secret",
                sa.String(),
                nullable=True,
                comment="This human's own bearer credential, reconciled from `users.<name>.secret` — what the served MCP endpoints and hook routers authenticate. Unique, so a bearer names exactly one user; NULL for a user registered only to link accounts. Stored plaintext by the same posture as the YAML that seeds it, `SecretStr` above the column.",
            )
        )
        batch_op.create_unique_constraint("uq_users_secret", ["secret"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_secret", type_="unique")
        batch_op.drop_column("secret")

    # ### end Alembic commands ###
