"""per-agent permission modes

Each provider keeps its own approval vocabulary rather than sharing one borrowed from
Claude, so `conversations.permission_mode` changes meaning: it is now written in the
vocabulary of the conversation's own agent, and goes nullable because the Codex scale
has no `default` member and no single server default fits every agent. NULL means
nothing declared, and the agent's configured default decides.

Nothing is carried — the column was never written by any code path, so every row holds
the old unified `default` and there is no operator intent in any of them. Each is
rewritten in its own agent's vocabulary instead, at the posture that agent's config
already defaults to, so a conversation reads as what it was running under all along.

An agent with no vocabulary keeps NULL: a native runtime's session is observed rather
than driven, and a posture it does not answer to is refused when the row is read.

`projects.permission_mode` goes without a replacement: the vocabulary belongs to the
agent classes, which are fixed, and the conversation is the executor that remembers what
its permission is now, so a project has nothing to say about it.

Revision ID: 02823d5dcce5
Revises: 1bad2a5f6be5
Create Date: 2026-08-11 20:10:41.612803

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02823d5dcce5"
down_revision: str | Sequence[str] | None = "1bad2a5f6be5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# What each agent's conversations start under — the value its config block already
# defaults to, spelled out here rather than imported, so this migration keeps saying
# what it did on the day it ran even after a default moves.
#
# Only agents that answer to a posture at all. One absent from this map is refused a
# posture on read (`octomate.types.permissions.check_mode`), so writing one would make
# its rows fail to load.
#
# The two native ids are the runtimes Octomate tails rather than drives, and they take
# their client's own default: a session Octomate only ever read was running under
# whatever the operator had it in, and the client's default is the honest guess when the
# transcript is already past. What the tailer reads off a live transcript overwrites
# this the next time that session says anything.
STARTING_POSTURES = {
    "inkling": "default",
    "claude": "default",
    "claude-native": "default",
    "codex": "user_review",
    "codex-native": "user_review",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "permission_mode", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("permission_mode")

    # ### end Alembic commands ###

    op.execute("UPDATE conversations SET permission_mode = NULL")
    for agent_tentacle_id, posture in STARTING_POSTURES.items():
        op.execute(
            sa.text(
                "UPDATE conversations SET permission_mode = :posture "
                "WHERE agent_tentacle_id = :agent_tentacle_id"
            ).bindparams(posture=posture, agent_tentacle_id=agent_tentacle_id)
        )


def downgrade() -> None:
    """Downgrade schema.

    A project's declared mode is not restored — the upgrade dropped it because nothing
    read it, and there is nowhere it could have been carried to. Every project comes
    back at the old unified `default`, which is what all of them held.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "permission_mode",
                sa.VARCHAR(),
                nullable=False,
                server_default="default",
                comment="Approval mode a conversation in this project starts under.",
            )
        )
    # ### end Alembic commands ###

    op.execute("UPDATE conversations SET permission_mode = 'default'")

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "permission_mode", existing_type=sa.VARCHAR(), nullable=False
        )
