"""todo_depends_on

Revision ID: b02034cd2b1e
Revises: d4e5f6a7b8c3
Create Date: 2026-04-17 20:17:00.222894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02034cd2b1e'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('depends_on', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'depends_on')
    # ### end Alembic commands ###
