"""stop registering projects from sessions

Every project is declared now (OCTO-45): a native session filing work no longer
registers the directory it ran in, so `origin` — which recorded whether a row was
declared or discovered by a Codex session — has nothing left to distinguish. Existing
rows lose that history with the column, which is the intent rather than a cost.

The downgrade restores the column with its old server default, so every row reads
`declared` — which by then is true of how rows come to exist, if not of how each one
did.

Revision ID: 9f541202305d
Revises: f54a9afc1e44
Create Date: 2026-08-20 12:10:15.259469

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f541202305d"
down_revision: str | Sequence[str] | None = "f54a9afc1e44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_column("origin")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "origin",
                sa.VARCHAR(),
                server_default=sa.text("'declared'"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###
