"""subagent run tree

A run gains its parent link (`parent_run_id` + `parent_tool_call_id` — the run
whose tool call spawned it, and which call it answers), and a conversation
gains the stable half of the same story: `subagent_id` (its identity within
(thread, agent)) and `parent_conversation_id` (whose context spawned it — not
derivable from runs, since a commission's parent is a different agent and the
parent's run row does not exist until that run finishes).

`subagent_id` is empty, not NULL, for the agent's own conversation — the
Thread.thread_id sentinel convention — so the existing unique constraint simply
widens to three columns under its own name. (Nullable would have needed two
indexes: NULLs are distinct in a unique constraint, so a second bare
(thread, agent, NULL) row would not collide.) The server_default backfills
existing rows; they were already unique on (thread, agent), so the widened
constraint builds over them as-is.

Autogenerated, then adjusted: this docstring, and a name for the self-FK
(autogen emitted `None`, which the downgrade cannot drop by).

Revision ID: 417719624acf
Revises: 3f1c8ad42b91
Create Date: 2026-07-17 23:03:02.080836

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "417719624acf"
down_revision: Union[str, Sequence[str], None] = "3f1c8ad42b91"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "parent_run_id",
                sa.String(),
                nullable=True,
                comment="The run whose tool call spawned this one (a subagent's turn). An unenforced reference, not a FK: native ingest supersedes a provisional parent by deleting and reinserting the same id across two commits, which an enforced constraint would block or cascade.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "parent_tool_call_id",
                sa.String(),
                nullable=True,
                comment="The ToolCallPart in the parent run's timeline this run answers, so a tool call can expand into its subagent's full timeline.",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_agent_runs_parent_run_id"), ["parent_run_id"], unique=False
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "subagent_id",
                sa.String(),
                server_default="",
                nullable=False,
                comment="Empty for the agent's own long-lived conversation in the thread; a subagent's stable identity for a context spawned by a run — Claude's agentId, Codex's child thread id, a commission's name. Not external_id: that is a mutable resumable handle, this is identity.",
            )
        )
        batch_op.add_column(
            sa.Column(
                "parent_conversation_id",
                sa.Uuid(),
                nullable=True,
                comment="The conversation whose run spawned this subagent's context — set iff subagent_id is. Not derivable from the runs: a commission's parent is a different agent, and the parent's run row does not exist until that run finishes. Which parent *turn* drove each child run stays on the run (parent_run_id); this is the stable whose-context half.",
            )
        )
        batch_op.drop_constraint(
            batch_op.f("uq_conversations_conversation_key"), type_="unique"
        )
        batch_op.create_unique_constraint(
            "uq_conversations_conversation_key",
            ["thread_id", "agent_tentacle_id", "subagent_id"],
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_parent_conversation_id"),
            ["parent_conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_subagent_id"), ["subagent_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_conversations_parent_conversation_id",
            "conversations",
            ["parent_conversation_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_conversations_parent_conversation_id", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_conversations_subagent_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_parent_conversation_id"))
        batch_op.drop_constraint("uq_conversations_conversation_key", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uq_conversations_conversation_key"),
            ["thread_id", "agent_tentacle_id"],
        )
        batch_op.drop_column("parent_conversation_id")
        batch_op.drop_column("subagent_id")

    with op.batch_alter_table("agent_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_agent_runs_parent_run_id"))
        batch_op.drop_column("parent_tool_call_id")
        batch_op.drop_column("parent_run_id")

    # ### end Alembic commands ###
