"""initial_schema

Revision ID: 924f7e1ce5ac
Revises: 
Create Date: 2026-07-03 12:15:06.858460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924f7e1ce5ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thread_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('platform_message_id', sa.String(), nullable=True),
    sa.Column('reply_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('actor_kind', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('agent_tentacle_id', sa.String(), nullable=True),
    sa.Column('sender', sa.JSON(), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.Column('raw', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thread_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thread_messages_actor_kind'), ['actor_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_agent_tentacle_id'), ['agent_tentacle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_message_text'), ['message_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_platform_message_id'), ['platform_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_reply_id'), ['reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_thread_messages_user_id'), ['user_id'], unique=False)

    op.create_table('threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_tentacle_id', sa.String(), nullable=False),
    sa.Column('chat_type', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_cursor_message_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_cursor_message_id'], ['thread_messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_tentacle_id', 'chat_type', 'chat_id', 'thread_id', name='uq_threads_key')
    )
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_threads_channel_tentacle_id'), ['channel_tentacle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_chat_type'), ['chat_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_source_cursor_message_id'), ['source_cursor_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_threads_updated_at'), ['updated_at'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('thread_id', sa.Uuid(), nullable=False, comment="The owning thread. A thread owns one conversation per agent, so (thread_id, agent_tentacle_id) is the conversation's identity."),
    sa.Column('agent_tentacle_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('permission_mode', sa.String(), nullable=False),
    sa.Column('allowed_tools', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'agent_tentacle_id', name='uq_conversations_conversation_key')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_agent_tentacle_id'), ['agent_tentacle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_thread_id'), ['thread_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_started_at'), ['started_at'], unique=False)

    op.create_table('deferred_action_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('agent_tentacle_id', sa.String(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source_address', sa.JSON(), nullable=False),
    sa.Column('target_address', sa.JSON(), nullable=False),
    sa.Column('target_mode', sa.String(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=True),
    sa.Column('requests', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deferred_action_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deferred_action_batches_agent_tentacle_id'), ['agent_tentacle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_action_batches_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_action_batches_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_action_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_action_batches_run_name'), ['run_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_action_batches_updated_at'), ['updated_at'], unique=False)

    op.create_table('todos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('active_form', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('parent_ref', sa.String(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'ref', name='uq_todos_conversation_ref')
    )
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_todos_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_parent_ref'), ['parent_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_ref'), ['ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_todos_updated_at'), ['updated_at'], unique=False)

    op.create_table('deferred_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_call_id', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('platform_message_id', sa.String(), nullable=True),
    sa.Column('responder_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['deferred_action_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deferred_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deferred_actions_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_actions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_actions_resolved_at'), ['resolved_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_actions_responder_id'), ['responder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_actions_tool_call_id'), ['tool_call_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_actions_tool_name'), ['tool_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deferred_actions_updated_at'), ['updated_at'], unique=False)

    op.create_table('model_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('parts', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('provider_url', sa.String(), nullable=True),
    sa.Column('provider_details', sa.JSON(), nullable=True),
    sa.Column('provider_response_id', sa.String(), nullable=True),
    sa.Column('finish_reason', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), server_default='assistant', nullable=False),
    sa.Column('message_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_message_text'), ['message_text'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_provider_response_id'), ['provider_response_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_messages_timestamp'), ['timestamp'], unique=False)

    op.create_table('channel_handoffs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('from_agent_tentacle_id', sa.String(), nullable=True),
    sa.Column('source_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('source_run_id', sa.String(), nullable=True),
    sa.Column('source_model_message_id', sa.Uuid(), nullable=True),
    sa.Column('to_agent_tentacle_id', sa.String(), nullable=False),
    sa.Column('to_model', sa.String(), nullable=True),
    sa.Column('target_conversation_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('hint', sa.String(), nullable=False),
    sa.Column('brief', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_model_message_id'], ['model_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_run_id'], ['agent_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channel_handoffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_handoffs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_from_agent_tentacle_id'), ['from_agent_tentacle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_source_conversation_id'), ['source_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_source_model_message_id'), ['source_model_message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_source_run_id'), ['source_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_target_conversation_id'), ['target_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_to_agent_tentacle_id'), ['to_agent_tentacle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_handoffs_to_model'), ['to_model'], unique=False)

    op.create_table('message_binding',
    sa.Column('thread_message_id', sa.Uuid(), nullable=False),
    sa.Column('model_message_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_message_id'], ['model_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_message_id'], ['thread_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_message_id', 'model_message_id', 'kind')
    )
    with op.batch_alter_table('message_binding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_binding_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_binding_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_binding_tool_call_id'), ['tool_call_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_binding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_binding_tool_call_id'))
        batch_op.drop_index(batch_op.f('ix_message_binding_run_id'))
        batch_op.drop_index(batch_op.f('ix_message_binding_created_at'))

    op.drop_table('message_binding')
    with op.batch_alter_table('channel_handoffs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_to_model'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_to_agent_tentacle_id'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_thread_id'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_target_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_source_run_id'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_source_model_message_id'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_source_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_from_agent_tentacle_id'))
        batch_op.drop_index(batch_op.f('ix_channel_handoffs_created_at'))

    op.drop_table('channel_handoffs')
    with op.batch_alter_table('model_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_model_messages_state'))
        batch_op.drop_index(batch_op.f('ix_model_messages_run_id'))
        batch_op.drop_index(batch_op.f('ix_model_messages_role'))
        batch_op.drop_index(batch_op.f('ix_model_messages_provider_response_id'))
        batch_op.drop_index(batch_op.f('ix_model_messages_provider_name'))
        batch_op.drop_index(batch_op.f('ix_model_messages_model_name'))
        batch_op.drop_index(batch_op.f('ix_model_messages_message_text'))
        batch_op.drop_index(batch_op.f('ix_model_messages_kind'))
        batch_op.drop_index(batch_op.f('ix_model_messages_conversation_id'))

    op.drop_table('model_messages')
    with op.batch_alter_table('deferred_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deferred_actions_updated_at'))
        batch_op.drop_index(batch_op.f('ix_deferred_actions_tool_name'))
        batch_op.drop_index(batch_op.f('ix_deferred_actions_tool_call_id'))
        batch_op.drop_index(batch_op.f('ix_deferred_actions_responder_id'))
        batch_op.drop_index(batch_op.f('ix_deferred_actions_resolved_at'))
        batch_op.drop_index(batch_op.f('ix_deferred_actions_kind'))
        batch_op.drop_index(batch_op.f('ix_deferred_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_deferred_actions_batch_id'))

    op.drop_table('deferred_actions')
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_todos_updated_at'))
        batch_op.drop_index(batch_op.f('ix_todos_ref'))
        batch_op.drop_index(batch_op.f('ix_todos_parent_ref'))
        batch_op.drop_index(batch_op.f('ix_todos_created_at'))
        batch_op.drop_index(batch_op.f('ix_todos_conversation_id'))

    op.drop_table('todos')
    with op.batch_alter_table('deferred_action_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deferred_action_batches_updated_at'))
        batch_op.drop_index(batch_op.f('ix_deferred_action_batches_run_name'))
        batch_op.drop_index(batch_op.f('ix_deferred_action_batches_created_at'))
        batch_op.drop_index(batch_op.f('ix_deferred_action_batches_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_deferred_action_batches_completed_at'))
        batch_op.drop_index(batch_op.f('ix_deferred_action_batches_agent_tentacle_id'))

    op.drop_table('deferred_action_batches')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_name'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_conversation_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_thread_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_agent_tentacle_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_threads_updated_at'))
        batch_op.drop_index(batch_op.f('ix_threads_thread_id'))
        batch_op.drop_index(batch_op.f('ix_threads_status'))
        batch_op.drop_index(batch_op.f('ix_threads_source_cursor_message_id'))
        batch_op.drop_index(batch_op.f('ix_threads_created_at'))
        batch_op.drop_index(batch_op.f('ix_threads_chat_type'))
        batch_op.drop_index(batch_op.f('ix_threads_chat_id'))
        batch_op.drop_index(batch_op.f('ix_threads_channel_tentacle_id'))

    op.drop_table('threads')
    with op.batch_alter_table('thread_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thread_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_reply_id'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_platform_message_id'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_message_text'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_direction'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_agent_tentacle_id'))
        batch_op.drop_index(batch_op.f('ix_thread_messages_actor_kind'))

    op.drop_table('thread_messages')
    # ### end Alembic commands ###
