"""the handoff names its source agent

`from_agent_tentacle_id` becomes `source_agent_tentacle_id`: the row already names
its source conversation, source run and source model message that way, and the
reflex state's handoff claim now does too, so the one column still saying `from`
was the odd one out. Same type, same index, now with the comment the model carries.

Autogenerate sees a rename as an add and a drop, which would lose the value on every
row, so the new column is added first, filled from the old one, and only then is the
old one dropped — in two batch passes, because SQLite recreates the table for each
and the copy has to land between them. Downgrade walks the same three steps back.

Revision ID: 1036c4c4f86b
Revises: 72af5e4bed47
Create Date: 2026-09-04 00:11:08.105883

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1036c4c4f86b"
down_revision: str | Sequence[str] | None = "72af5e4bed47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel_handoffs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source_agent_tentacle_id",
                sa.String(),
                nullable=True,
                comment="The agent whose turn decided this handoff. NULL when a route claimed the thread itself and nobody handed it over.",
            )
        )
        batch_op.create_index(
            batch_op.f("ix_channel_handoffs_source_agent_tentacle_id"),
            ["source_agent_tentacle_id"],
            unique=False,
        )

    op.execute(
        "UPDATE channel_handoffs SET source_agent_tentacle_id = from_agent_tentacle_id"
    )

    with op.batch_alter_table("channel_handoffs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_handoffs_from_agent_tentacle_id"))
        batch_op.drop_column("from_agent_tentacle_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel_handoffs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("from_agent_tentacle_id", sa.VARCHAR(), nullable=True)
        )
        batch_op.create_index(
            batch_op.f("ix_channel_handoffs_from_agent_tentacle_id"),
            ["from_agent_tentacle_id"],
            unique=False,
        )

    op.execute(
        "UPDATE channel_handoffs SET from_agent_tentacle_id = source_agent_tentacle_id"
    )

    with op.batch_alter_table("channel_handoffs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_handoffs_source_agent_tentacle_id"))
        batch_op.drop_column("source_agent_tentacle_id")

    # ### end Alembic commands ###
