"""threads and interactions

Revision ID: 05d7387410ca
Revises: a31510d5944c
Create Date: 2026-03-26 15:39:54.503547

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "05d7387410ca"
down_revision: Union[str, Sequence[str], None] = "a31510d5944c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threads",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tentacle_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=True),
        sa.Column("thread_id", sa.String(), nullable=True),
        sa.Column("chat_id", sa.String(), nullable=True),
        sa.Column("owner_tentacle", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tentacle_id",
            "user_id",
            "group_id",
            "thread_id",
            "chat_id",
            name="uq_threads_session_key",
        ),
    )
    op.create_index(op.f("ix_threads_chat_id"), "threads", ["chat_id"], unique=False)
    op.create_index(op.f("ix_threads_group_id"), "threads", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_threads_owner_tentacle"), "threads", ["owner_tentacle"], unique=False
    )
    op.create_index(
        op.f("ix_threads_tentacle_id"), "threads", ["tentacle_id"], unique=False
    )
    op.create_index(
        op.f("ix_threads_thread_id"), "threads", ["thread_id"], unique=False
    )
    op.create_index(op.f("ix_threads_user_id"), "threads", ["user_id"], unique=False)
    op.create_table(
        "confirmations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("confirmation_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("tool_name", sa.String(), nullable=False),
        sa.Column("tool_call_id", sa.String(), nullable=False),
        sa.Column("args", sa.JSON(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("skill", sa.String(), nullable=False),
        sa.Column("approvers", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_confirmations_confirmation_id"),
        "confirmations",
        ["confirmation_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_confirmations_status"), "confirmations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_confirmations_thread_id"), "confirmations", ["thread_id"], unique=False
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("answer", sa.String(), nullable=True),
        sa.Column("responder_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questions_question_id"), "questions", ["question_id"], unique=True
    )
    op.create_index(op.f("ix_questions_status"), "questions", ["status"], unique=False)
    op.create_index(
        op.f("ix_questions_thread_id"), "questions", ["thread_id"], unique=False
    )
    op.create_table(
        "todos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("todo_id", sa.String(), nullable=False),
        sa.Column("thread_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("active_form", sa.String(), nullable=True),
        sa.Column("assignee", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todos_status"), "todos", ["status"], unique=False)
    op.create_index(op.f("ix_todos_thread_id"), "todos", ["thread_id"], unique=False)
    op.create_index(op.f("ix_todos_todo_id"), "todos", ["todo_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todos_todo_id"), table_name="todos")
    op.drop_index(op.f("ix_todos_thread_id"), table_name="todos")
    op.drop_index(op.f("ix_todos_status"), table_name="todos")
    op.drop_table("todos")
    op.drop_index(op.f("ix_questions_thread_id"), table_name="questions")
    op.drop_index(op.f("ix_questions_status"), table_name="questions")
    op.drop_index(op.f("ix_questions_question_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_confirmations_thread_id"), table_name="confirmations")
    op.drop_index(op.f("ix_confirmations_status"), table_name="confirmations")
    op.drop_index(op.f("ix_confirmations_confirmation_id"), table_name="confirmations")
    op.drop_table("confirmations")
    op.drop_index(op.f("ix_threads_user_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_thread_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_tentacle_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_owner_tentacle"), table_name="threads")
    op.drop_index(op.f("ix_threads_group_id"), table_name="threads")
    op.drop_index(op.f("ix_threads_chat_id"), table_name="threads")
    op.drop_table("threads")
    # ### end Alembic commands ###
