"""add role and message_text to model_messages

Revision ID: 197cd8f30548
Revises: 6fadf2912338
Create Date: 2026-06-14 22:51:04.021871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197cd8f30548'
down_revision: Union[str, Sequence[str], None] = '6fadf2912338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_messages', sa.Column('role', sa.String(), server_default='assistant', nullable=False))
    op.add_column('model_messages', sa.Column('message_text', sa.String(), nullable=True))
    op.create_index(op.f('ix_model_messages_message_text'), 'model_messages', ['message_text'], unique=False)
    op.create_index(op.f('ix_model_messages_role'), 'model_messages', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_messages_role'), table_name='model_messages')
    op.drop_index(op.f('ix_model_messages_message_text'), table_name='model_messages')
    op.drop_column('model_messages', 'message_text')
    op.drop_column('model_messages', 'role')
    # ### end Alembic commands ###
